language: node_js
node_js:
  - "5.5"
services:
  - redis-server
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    # packages:
    # - gcc-4.8
    # - g++-4.8
  # code_climate:
  #   repo_token:
# after_script:
#   - codeclimate-test-reporter < coverage/lcov.info
env:
  - TEST_DIR=backend
  - TEST_DIR=frontend
script: cd $TEST_DIR && npm install && npm test
